Repository microsoft/DirectXShaderCompiler, pull requests merged in 2018-08, with the labels that each got.

#1474 [linux-port] DxilContainer/ModuleTest on Unix
  .travis.yml
  tools/clang/unittests/HLSL/CMakeLists.txt
  tools/clang/unittests/HLSL/DxilContainerTest.cpp
  tools/clang/unittests/HLSL/DxilModuleTest.cpp
Labels: linux-port

#1475 [spirv] Update mapping manual w.r.t. debugging and options
  docs/SPIR-V.rst
  include/dxc/Support/HLSLOptions.td
Labels: spirv

#1470 Fix random ordering of disassembly
  lib/HLSL/DxilContainerAssembler.cpp
  lib/HLSL/DxilPreserveAllOutputs.cpp
Labels: enhancement

#1479 [linux-port] Better match Windows char conversion
  include/dxc/Support/WinAdapter.h
  lib/DxcSupport/Unicode.cpp
  lib/DxcSupport/WinAdapter.cpp
  tools/clang/test/CodeGenHLSL/quick-test/assignCast.hlsl
Labels: linux-port

#1481 [linux-port] Enable OptionsTest on Unix
  tools/clang/unittests/HLSL/CMakeLists.txt
  tools/clang/unittests/HLSL/OptionsTest.cpp
Labels: linux-port

#1477 Change CreateBlobWithEncodingFromPinned argument to LPCVOID; silence lost const warnings
  include/dxc/dxcapi.h
  tools/clang/tools/dxcompiler/dxclibrary.cpp
  tools/clang/unittests/HLSL/CompilerTest.cpp
  tools/clang/unittests/HLSL/ExecutionTest.cpp
  tools/clang/unittests/HLSL/FileCheckerTest.cpp
  tools/clang/unittests/HLSL/RewriterTest.cpp
  tools/clang/unittests/HLSL/ShaderOpTest.cpp
  tools/clang/unittests/HLSL/ValidationTest.cpp
Labels: linux-port

#1485 [apple-port] Format locales for Apple
  lib/DxcSupport/WinAdapter.cpp
Labels: linux-port

#1483 [linux-port] Enable CompilerTest for Unix
  tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_BuildGridCS.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_BuildGridIndicesCS.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ClearGridIndicesCS.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_DensityCS_Grid.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_DensityCS_Shared.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_DensityCS_Simple.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ForceCS_Grid.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ForceCS_Shared.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_ForceCS_Simple.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_IntegrateCS.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/FluidCS11_RearrangeParticlesCS.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/POM_PS.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/POM_VS.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/Particle_GS.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/Particle_PS.hlsl
  tools/clang/test/CodeGenHLSL/Samples/DX11/Particle_VS.hlsl
  tools/clang/test/CodeGenHLSL/scalarOnVecIntrisic.hlsl
  tools/clang/unittests/HLSL/CMakeLists.txt
  tools/clang/unittests/HLSL/CompilerTest.cpp
  tools/clang/unittests/HLSL/WEXAdapter.h
Labels: linux-port

#1505 [spirv] Reuse existing function to find bitwidth
  tools/clang/lib/SPIRV/SPIRVEmitter.cpp
Labels: spirv

#1515 [spirv] Add cl options into the emitted SPIRV.
  tools/clang/include/clang/SPIRV/EmitSPIRVOptions.h
  tools/clang/include/clang/SPIRV/ModuleBuilder.h
  tools/clang/include/clang/SPIRV/Structure.h
  tools/clang/lib/SPIRV/ModuleBuilder.cpp
  tools/clang/lib/SPIRV/SPIRVEmitter.cpp
  tools/clang/lib/SPIRV/Structure.cpp
  tools/clang/test/CodeGenSPIRV/spirv.debug.cl-option.hlsl
  tools/clang/tools/dxcompiler/dxcompilerobj.cpp
  tools/clang/unittests/SPIRV/CodeGenSPIRVTest.cpp
  tools/clang/unittests/SPIRV/ModuleBuilderTest.cpp
  tools/clang/unittests/SPIRV/WholeFileTestFixture.cpp
Labels: spirv

#1521 [spirv] Cleanup of cl option handling for SPIRV.
  include/dxc/Support/HLSLOptions.h
  include/dxc/Support/SPIRVOptions.h
  lib/DxcSupport/HLSLOptions.cpp
  tools/clang/include/clang/Frontend/CodeGenOptions.h
  tools/clang/include/clang/SPIRV/EmitSPIRVAction.h
  tools/clang/include/clang/SPIRV/FeatureManager.h
  tools/clang/include/clang/SPIRV/ModuleBuilder.h
  tools/clang/include/clang/SPIRV/Structure.h
  tools/clang/lib/SPIRV/CMakeLists.txt
  tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
  tools/clang/lib/SPIRV/DeclResultIdMapper.h
  tools/clang/lib/SPIRV/EmitSPIRVAction.cpp
  tools/clang/lib/SPIRV/EmitSPIRVOptions.cpp
  tools/clang/lib/SPIRV/FeatureManager.cpp
  tools/clang/lib/SPIRV/ModuleBuilder.cpp
  tools/clang/lib/SPIRV/SPIRVEmitter.cpp
  tools/clang/lib/SPIRV/SPIRVEmitter.h
  tools/clang/lib/SPIRV/SpirvEvalInfo.h
  tools/clang/lib/SPIRV/TypeTranslator.cpp
  tools/clang/lib/SPIRV/TypeTranslator.h
  tools/clang/tools/dxcompiler/dxcompilerobj.cpp
Labels: spirv
