Repository microsoft/DirectXShaderCompiler, pull requests merged in 2022-12, with the labels that each got.

#4844 [HLSL2021] UDT template parms follow C++ rules
  tools/clang/lib/Sema/SemaTemplate.cpp
  tools/clang/test/HLSLFileCheck/hlsl/template/4771-udt-parameter-validation.hlsl
Labels: hlsl2021, for-release

#4774 Fill in RequiredFeatureFlags in library function reflection
  lib/HLSL/DxilContainerReflection.cpp
  tools/clang/test/HLSLFileCheck/d3dreflect/lib_global.hlsl
  tools/clang/test/HLSLFileCheck/d3dreflect/lib_requires_flags.hlsl
  tools/clang/unittests/HLSLTestLib/D3DReflectionDumper.cpp
Labels: for-release

#4752 Remove assumption that templates are never UDTs
  tools/clang/include/clang/AST/HlslTypes.h
  tools/clang/lib/AST/HlslTypes.cpp
  tools/clang/lib/CodeGen/CGHLSLMS.cpp
  tools/clang/lib/SPIRV/AstTypeProbe.cpp
  tools/clang/lib/SPIRV/SpirvEmitter.cpp
  tools/clang/test/HLSL/template-udt-load.hlsl
  tools/clang/test/HLSLFileCheck/hlsl/template/ByteAddressBufferLoad.hlsl
  tools/clang/test/HLSLFileCheck/shader_targets/raytracing/builtin-ray-types-anyhit.hlsl
  tools/clang/test/HLSLFileCheck/shader_targets/raytracing/builtin-ray-types-callable.hlsl
  tools/clang/test/HLSLFileCheck/shader_targets/raytracing/builtin-ray-types-miss.hlsl
  tools/clang/unittests/HLSL/VerifierTest.cpp
Labels: hlsl2021, for-release

#4859 Fix enum scope used inside template function.
  tools/clang/lib/Sema/TreeTransform.h
  tools/clang/test/HLSLFileCheck/hlsl/template/enum-scope-in-template-func.hlsl
Labels: hlsl2021, for-release

#4736 Enable -ftime-report flag
  include/dxc/Support/HLSLOptions.h
  include/dxc/Support/HLSLOptions.td
  include/dxc/Support/dxcapi.impl.h
  include/dxc/dxcapi.h
  lib/DxcSupport/HLSLOptions.cpp
  tools/clang/test/DXC/ftime-report.hlsl
  tools/clang/test/lit.cfg
  tools/clang/tools/dxclib/dxc.cpp
  tools/clang/tools/dxcompiler/dxcompilerobj.cpp
  tools/clang/unittests/HLSL/CompilerTest.cpp
  utils/hct/hcttestcmds.cmd
Labels: for-release

#4870 [SPIR-V] Fix invalid HLSL in test
  tools/clang/test/CodeGenSPIRV/spirv.legal.sbuffer.counter.method.hlsl
Labels: spirv

#4882 Enable 2021 operator intrinsics in older modes
  tools/clang/lib/Sema/SemaHLSL.cpp
  tools/clang/test/CodeGenSPIRV/intrinsics.and.hlsl
  tools/clang/test/CodeGenSPIRV/intrinsics.or.hlsl
  tools/clang/test/CodeGenSPIRV/intrinsics.select.hlsl
Labels: for-release

#4880 Cherry-pick -ftime-report and -ftime-trace patches to Release branch
  include/dxc/Support/HLSLOptions.h
  include/dxc/Support/HLSLOptions.td
  include/dxc/Support/dxcapi.impl.h
  include/dxc/dxcapi.h
  include/llvm/Support/TimeProfiler.h
  include/llvm/Support/raw_ostream.h
  lib/Analysis/IPA/CallGraphSCCPass.cpp
  lib/DxcSupport/HLSLOptions.cpp
  lib/IR/LegacyPassManager.cpp
  lib/Support/CMakeLists.txt
  lib/Support/TimeProfiler.cpp
  tools/clang/include/clang/Driver/Options.td
  tools/clang/include/clang/Frontend/CodeGenOptions.def
  tools/clang/include/clang/Frontend/FrontendOptions.h
  tools/clang/lib/CodeGen/BackendUtil.cpp
  tools/clang/lib/CodeGen/CodeGenModule.cpp
  tools/clang/lib/Driver/Tools.cpp
  tools/clang/lib/Frontend/CompilerInstance.cpp
  tools/clang/lib/Frontend/CompilerInvocation.cpp
  tools/clang/lib/Parse/ParseAST.cpp
  tools/clang/lib/Parse/ParseDeclCXX.cpp
  tools/clang/lib/Parse/ParseTemplate.cpp
  tools/clang/lib/Sema/Sema.cpp
  tools/clang/lib/Sema/SemaTemplateInstantiate.cpp
  tools/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp
  tools/clang/test/DXC/Inputs/empty.h
  tools/clang/test/DXC/ftime-report.hlsl
  tools/clang/test/DXC/ftime-trace.hlsl
  tools/clang/test/DXC/show-includes.hlsl
  tools/clang/test/lit.cfg
  tools/clang/tools/dxclib/dxc.cpp
  tools/clang/tools/dxcompiler/dxcompilerobj.cpp
  tools/clang/unittests/HLSL/CompilerTest.cpp
  utils/hct/hcttestcmds.cmd
Labels: for-release

#4885 Enable 2021 operator intrinsics in older modes (#4882)
  tools/clang/lib/Sema/SemaHLSL.cpp
  tools/clang/test/CodeGenSPIRV/intrinsics.and.hlsl
  tools/clang/test/CodeGenSPIRV/intrinsics.or.hlsl
  tools/clang/test/CodeGenSPIRV/intrinsics.select.hlsl
Labels: for-release
