Repository microsoft/DirectXShaderCompiler, pull requests merged in 2023-07, with the labels that each got.

#5296 Add macro to disable usage of allocator overrides
  CMakeLists.txt
  include/dxc/CMakeLists.txt
  include/dxc/Support/WinFunctions.h
  include/dxc/Support/WinIncludes.h
  include/dxc/Support/microcom.h
  include/dxc/WinAdapter.h
  include/dxc/config.h.cmake
  lib/DxcSupport/CMakeLists.txt
  lib/DxcSupport/WinFunctions.cpp
  lib/DxcSupport/WinIncludes.cpp
  lib/DxcSupport/dxcmem.cpp
  projects/dxilconv/tools/dxilconv/dxilconv.cpp
  tools/clang/tools/dxclib/dxc.cpp
  tools/clang/tools/dxcompiler/DXCompiler.cpp
  tools/clang/tools/dxcompiler/dxcapi.cpp
  tools/clang/tools/dxcompiler/dxclinker.cpp
  tools/clang/tools/dxrfallbackcompiler/DXCompiler.cpp
  tools/clang/unittests/HLSL/ValidationTest.cpp
  tools/clang/unittests/HLSLExec/ExecutionTest.cpp
  tools/clang/unittests/dxc_batch/dxc_batch.cpp
Labels: build

#5468 Add TransformUtils dependency to DxilContainer for Linux builds
  lib/DxilContainer/LLVMBuild.txt
Labels: for-release

#5466 Make HLSL 2021 the default language mode
  include/dxc/Support/HLSLVersion.h
  tools/clang/test/DXC/VersionMacro.hlsl
Labels: for-release

#5454 Allow new/delete operators to be called before DllMain
  include/dxc/Support/Global.h
  lib/DxcSupport/dxcmem.cpp
  tools/clang/tools/dxcompiler/DXCompiler.cpp
  tools/clang/tools/dxlib-sample/dxlib_sample.cpp
  tools/clang/tools/dxrfallbackcompiler/DXCompiler.cpp
Labels: for-release

#5446 [SPIR-V] Handle non-global ConstantBuffer
  tools/clang/lib/SPIRV/AstTypeProbe.cpp
  tools/clang/lib/SPIRV/DeclResultIdMapper.cpp
  tools/clang/lib/SPIRV/DeclResultIdMapper.h
  tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
  tools/clang/lib/SPIRV/LowerTypeVisitor.h
  tools/clang/lib/SPIRV/SpirvEmitter.cpp
  tools/clang/lib/SPIRV/SpirvEmitter.h
  tools/clang/test/CodeGenSPIRV/spirv.legal.cbuffer.hlsl
  tools/clang/test/CodeGenSPIRV/spirv.legal.tbuffer.hlsl
  tools/clang/test/CodeGenSPIRV/type.constant-buffer.assign.hlsl
  tools/clang/test/CodeGenSPIRV/type.constant-buffer.bindless.array.hlsl
  tools/clang/test/CodeGenSPIRV/type.constant-buffer.return.hlsl
  tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
Labels: spirv

#5463 Fix mutex use after free in llvm_shutdown
  include/llvm/Support/ManagedStatic.h
  lib/Support/ManagedStatic.cpp
Labels: for-release
